version: "2"

run:
  timeout: 5m
  go: "1.23"

formatters:
  enable:
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/sevigo/code-warden

linters:
  enable:
    - govet
    - ineffassign
    - misspell
    - unused
    - staticcheck
    - errcheck

issues:
  max-same-issues: 0
  
  exclude-rules:
    - path: '_test\.go'
      linters:
        - errcheck