version: 2

run:
  timeout: 5m
  go: "1.23"

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - unused
    - staticcheck
    - errcheck

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/sevigo/code-warden

issues:
  exclude-use-default: false
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck