services:
  ollama-setup:
    image: ollama/ollama
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - cost-warden-net

    entrypoint: /bin/sh 
    
    command: >
      -c "
        ollama serve &
        sleep 5 &&
        ollama pull gemma3:latest &&
        ollama pull nomic-embed-text &&
        pkill ollama
      "

volumes:
  ollama-data:
    external: false 

networks:
  cost-warden-net:
    external: false