-- Agent Session and Design Document Schema
-- Run these migrations to enable warden agent functionality

-- Agent sessions table for session persistence and audit
CREATE TABLE IF NOT EXISTS agent_sessions (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    task_type       VARCHAR(50) NOT NULL,
    repo_owner      VARCHAR(255) NOT NULL,
    repo_name       VARCHAR(255) NOT NULL,
    branch          VARCHAR(255),
    issue_number    INTEGER,
    
    status          VARCHAR(50) NOT NULL DEFAULT 'pending',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at    TIMESTAMPTZ,
    
    -- Task inputs (JSON)
    task_inputs     JSONB,
    
    -- Result (JSON)
    result          JSONB,
    
    -- Error message
    error           TEXT,
    
    -- Iteration tracking
    iterations      INTEGER DEFAULT 0,
    final_verdict   VARCHAR(50),
    
    -- Session log (tool calls, responses, events)
    session_log     JSONB DEFAULT '[]'::jsonb
);

-- Indexes for agent_sessions
CREATE INDEX IF NOT EXISTS idx_agent_sessions_repo ON agent_sessions(repo_owner, repo_name);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_status ON agent_sessions(status);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_created ON agent_sessions(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_type ON agent_sessions(task_type);

-- Design documents generated by agents during exploration
CREATE TABLE IF NOT EXISTS agent_design_documents (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id      UUID REFERENCES agent_sessions(id) ON DELETE SET NULL,
    
    doc_type        VARCHAR(50) NOT NULL,
    title           VARCHAR(255) NOT NULL,
    content         TEXT NOT NULL,
    summary         TEXT,
    
    -- Related symbols and directories for linking
    symbols         TEXT[],
    directories     TEXT[],
    confidence      FLOAT DEFAULT 0.0,
    
    generated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    generated_by    VARCHAR(100),
    
    -- Vector store reference (link to Qdrant document)
    vector_id       VARCHAR(255),
    
    -- Repository reference
    repo_owner      VARCHAR(255) NOT NULL,
    repo_name       VARCHAR(255) NOT NULL
);

-- Indexes for agent_design_documents
CREATE INDEX IF NOT EXISTS idx_design_docs_type ON agent_design_documents(doc_type);
CREATE INDEX IF NOT EXISTS idx_design_docs_session ON agent_design_documents(session_id);
CREATE INDEX IF NOT EXISTS idx_design_docs_repo ON agent_design_documents(repo_owner, repo_name);
CREATE INDEX IF NOT EXISTS idx_design_docs_generated ON agent_design_documents(generated_at DESC);

-- Trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_agent_session_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER agent_sessions_updated_at
    BEFORE UPDATE ON agent_sessions
    FOR EACH ROW
    EXECUTE FUNCTION update_agent_session_updated_at();