// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"
	"github.com/sevigo/code-warden/internal/app"
	"github.com/sevigo/code-warden/internal/config"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context) (*app.App, func(), error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return nil, nil, err
	}
	loggerConfig := provideLoggerConfig(configConfig)
	writer := provideLogWriter()
	logger := provideDefaultSlogLogger(loggerConfig, writer)
	appApp, cleanup, err := app.NewApp(ctx, configConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	return appApp, func() {
		cleanup()
	}, nil
}
