// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"
	"fmt"
	"github.com/jmoiron/sqlx"
	"github.com/sevigo/code-warden/internal/app"
	"github.com/sevigo/code-warden/internal/config"
	"github.com/sevigo/code-warden/internal/core"
	"github.com/sevigo/code-warden/internal/db"
	"github.com/sevigo/code-warden/internal/gitutil"
	"github.com/sevigo/code-warden/internal/globalmcp"
	"github.com/sevigo/code-warden/internal/jobs"
	"github.com/sevigo/code-warden/internal/llm"
	"github.com/sevigo/code-warden/internal/logger"
	"github.com/sevigo/code-warden/internal/rag"
	"github.com/sevigo/code-warden/internal/repomanager"
	"github.com/sevigo/code-warden/internal/server"
	"github.com/sevigo/code-warden/internal/storage"
	"github.com/sevigo/goframe/embeddings"
	"github.com/sevigo/goframe/httpclient"
	"github.com/sevigo/goframe/llms"
	"github.com/sevigo/goframe/llms/gemini"
	"github.com/sevigo/goframe/llms/ollama"
	"github.com/sevigo/goframe/parsers"
	"github.com/sevigo/goframe/schema"
	"github.com/sevigo/goframe/textsplitter"
	"github.com/sevigo/goframe/vectorstores/qdrant"
	"io"
	"log/slog"
	"os"
	"time"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context) (*app.App, func(), error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return nil, nil, err
	}
	dbConfig := provideDBConfig(configConfig)
	dbDB, cleanup, err := db.NewDatabase(dbConfig)
	if err != nil {
		return nil, nil, err
	}
	sqlxDB := provideSQLXDB(dbDB)
	store := storage.NewStore(sqlxDB)
	loggerConfig := provideLoggerConfig(configConfig)
	writer := provideLogWriter(configConfig)
	logger := provideSlogLogger(loggerConfig, writer)
	embedder, err := provideEmbedder(ctx, configConfig, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	vectorStore := provideVectorStore(configConfig, embedder, logger)
	client := gitutil.NewClient(logger)
	repoManager := repomanager.New(configConfig, store, vectorStore, client, logger)
	promptManager, err := llm.NewPromptManager()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	model, err := provideGeneratorLLM(ctx, configConfig, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	reranker, err := provideReranker(ctx, configConfig, logger, promptManager)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	parserRegistry, err := provideParserRegistry(logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	textSplitter, err := provideTextSplitter(parserRegistry, model, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	service, err := rag.NewService(configConfig, promptManager, vectorStore, store, model, reranker, parserRegistry, textSplitter, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	workspaceRegistry := provideWorkspaceRegistry(logger)
	job := jobs.NewReviewJob(configConfig, service, store, vectorStore, repoManager, logger, workspaceRegistry)
	jobDispatcher := jobs.NewDispatcher(ctx, job, configConfig, logger)
	serverServer := server.NewServerWithStore(ctx, configConfig, jobDispatcher, job, store, service, repoManager, client, logger)
	globalmcpServer, err := provideGlobalMCPServer(ctx, configConfig, logger, workspaceRegistry, store, vectorStore, service)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	appApp := app.NewApp(configConfig, dbDB, store, vectorStore, repoManager, jobDispatcher, service, serverServer, client, globalmcpServer, logger)
	return appApp, func() {
		cleanup()
	}, nil
}

// wire.go:

func parseHeaderTimeout(s string, logger *slog.Logger) time.Duration {
	d, err := time.ParseDuration(s)
	if err != nil {
		logger.Warn("invalid http_response_header_timeout, using default 180s", "error", err)
		return 180 * time.Second
	}
	return d
}

func parseRequestTimeout(s string, logger *slog.Logger) time.Duration {
	if s == "" {
		return 0
	}
	d, err := time.ParseDuration(s)
	if err != nil {
		logger.Warn("invalid http_request_timeout, using no timeout", "error", err)
		return 0
	}
	return d
}

func provideSQLXDB(db2 *db.DB) *sqlx.DB {
	return db2.DB
}

func provideVectorStore(cfg *config.Config, embedder embeddings.Embedder, logger *slog.Logger) storage.VectorStore {
	var batchConfig *qdrant.BatchConfig
	if cfg.AI.EmbedderProvider == "gemini" {
		batchConfig = &qdrant.BatchConfig{
			BatchSize:               256,
			MaxConcurrency:          4,
			EmbeddingBatchSize:      90,
			EmbeddingMaxConcurrency: 1,
			RetryAttempts:           qdrant.DefaultRetryAttempts,
			RetryDelay:              qdrant.DefaultRetryDelay,
			RetryJitter:             qdrant.DefaultRetryJitter,
			MaxRetryDelay:           qdrant.DefaultMaxRetryDelay,
		}
	} else {
		batchConfig = &qdrant.BatchConfig{
			BatchSize:               512,
			MaxConcurrency:          8,
			EmbeddingBatchSize:      64,
			EmbeddingMaxConcurrency: 8,
			RetryAttempts:           qdrant.DefaultRetryAttempts,
			RetryDelay:              qdrant.DefaultRetryDelay,
			RetryJitter:             qdrant.DefaultRetryJitter,
			MaxRetryDelay:           qdrant.DefaultMaxRetryDelay,
		}
	}

	return storage.NewQdrantVectorStore(
		cfg,
		logger, storage.WithBatchConfig(batchConfig), storage.WithInitialEmbedder(cfg.AI.EmbedderModel, embedder), storage.WithQdrantOptions(qdrant.WithTimeout(60*time.Second), qdrant.WithKeepaliveTime(15*time.Second), qdrant.WithKeepaliveTimeout(5*time.Second), qdrant.WithPoolSize(20)),
	)
}

func provideGeneratorLLM(ctx context.Context, cfg *config.Config, logger *slog.Logger) (llms.Model, error) {
	switch cfg.AI.LLMProvider {
	case "gemini":
		if cfg.AI.GeminiAPIKey == "" {
			return nil, fmt.Errorf("GEMINI_API_KEY is not set")
		}
		return gemini.New(ctx, gemini.WithModel(cfg.AI.GeneratorModel), gemini.WithAPIKey(cfg.AI.GeminiAPIKey))
	case "ollama":
		headerTimeout := parseHeaderTimeout(cfg.AI.HTTPResponseHeaderTimeout, logger)
		requestTimeout := parseRequestTimeout(cfg.AI.HTTPRequestTimeout, logger)

		logger.Info("configuring Ollama HTTP client for generator",
			"response_header_timeout", headerTimeout,
			"request_timeout", requestTimeout,
			"model", cfg.AI.GeneratorModel,
		)

		clientCfg := httpclient.NewConfig(httpclient.WithResponseHeaderTimeout(headerTimeout))

		if requestTimeout > 0 {
			clientCfg.Timeout = requestTimeout
		} else {
			clientCfg.Timeout = 0
		}

		opts := []ollama.Option{ollama.WithServerURL(cfg.AI.OllamaHost), ollama.WithAPIKey(cfg.AI.OllamaAPIKey), ollama.WithHTTPClient(httpclient.NewClient(clientCfg)), ollama.WithModel(cfg.AI.GeneratorModel), ollama.WithLogger(logger), ollama.WithRetryAttempts(3), ollama.WithRetryDelay(2 * time.Second)}

		if cfg.AI.EnableThinking {
			opts = append(opts, ollama.WithThinking(true))
			if cfg.AI.ThinkingEffort != "" {
				opts = append(opts, ollama.WithReasoningEffort(cfg.AI.ThinkingEffort))
			}
		}

		if cfg.AI.ModelKeepAlive != "" {
			opts = append(opts, ollama.WithKeepAlive(cfg.AI.ModelKeepAlive))
		}
		return ollama.New(opts...)
	default:
		return nil, fmt.Errorf("unsupported LLM provider: %s", cfg.AI.LLMProvider)
	}
}

func provideEmbedder(ctx context.Context, cfg *config.Config, logger *slog.Logger) (embeddings.Embedder, error) {
	var embedderLLM embeddings.Embedder
	var err error

	switch cfg.AI.EmbedderProvider {
	case "gemini":
		embedderLLM, err = gemini.New(ctx, gemini.WithEmbeddingModel(cfg.AI.EmbedderModel), gemini.WithAPIKey(cfg.AI.GeminiAPIKey))
	case "ollama":
		headerTimeout := parseHeaderTimeout(cfg.AI.HTTPResponseHeaderTimeout, logger)
		requestTimeout := parseRequestTimeout(cfg.AI.HTTPRequestTimeout, logger)

		logger.Info("configuring Ollama HTTP client for embedder",
			"response_header_timeout", headerTimeout,
			"request_timeout", requestTimeout,
			"model", cfg.AI.EmbedderModel,
		)

		clientCfg := httpclient.NewConfig(httpclient.WithResponseHeaderTimeout(headerTimeout))

		if requestTimeout > 0 {
			clientCfg.Timeout = requestTimeout
		} else {
			clientCfg.Timeout = 0
		}

		opts := []ollama.Option{ollama.WithServerURL(cfg.AI.OllamaHost), ollama.WithAPIKey(cfg.AI.OllamaAPIKey), ollama.WithModel(cfg.AI.EmbedderModel), ollama.WithHTTPClient(httpclient.NewClient(clientCfg)), ollama.WithLogger(logger), ollama.WithRetryAttempts(3), ollama.WithRetryDelay(2 * time.Second)}

		if cfg.AI.ModelKeepAlive != "" {
			opts = append(opts, ollama.WithKeepAlive(cfg.AI.ModelKeepAlive))
		}
		embedderLLM, err = ollama.New(opts...)
	default:
		return nil, fmt.Errorf("unsupported embedder provider: %s", cfg.AI.EmbedderProvider)
	}

	if err != nil {
		return nil, fmt.Errorf("failed to create embedder LLM: %w", err)
	}
	return embeddings.NewEmbedder(embedderLLM)
}

func provideParserRegistry(logger *slog.Logger) (parsers.ParserRegistry, error) {
	return parsers.RegisterLanguagePlugins(logger)
}

func provideTextSplitter(registry parsers.ParserRegistry, model llms.Model, logger *slog.Logger) (textsplitter.TextSplitter, error) {
	tokenizer := llm.NewOllamaTokenizerAdapter(model)
	splitter, err := textsplitter.NewCodeAware(
		registry,
		tokenizer,
		logger, textsplitter.WithChunkSize(2000), textsplitter.WithChunkOverlap(200), textsplitter.WithParentContextConfig(textsplitter.ParentContextConfig{Enabled: true}),
	)
	if err != nil {
		return nil, err
	}
	return splitter, nil
}

func provideLoggerConfig(cfg *config.Config) logger.Config {
	return cfg.Logging
}

func provideDBConfig(cfg *config.Config) *config.DBConfig {
	return &cfg.Database
}

func provideLogWriter(cfg *config.Config) io.Writer {
	switch cfg.Logging.Output {
	case "stdout":
		return os.Stdout
	case "stderr":
		return os.Stderr
	case "file":
		f, err := os.OpenFile("code-warden.log", os.O_WRONLY|os.O_CREATE|os.O_APPEND, 0600)
		if err != nil {
			fmt.Fprintf(os.Stderr, "failed to open log file: %v, falling back to stdout\n", err)
			return os.Stdout
		}
		return f
	default:
		return os.Stdout
	}
}

func provideSlogLogger(loggerConfig logger.Config, writer io.Writer) *slog.Logger {
	return logger.NewLogger(loggerConfig, writer)
}

func provideGlobalMCPServer(ctx context.Context, cfg *config.Config, logger2 *slog.Logger, registry *globalmcp.WorkspaceRegistry, store storage.Store, vectorStore storage.VectorStore, ragService rag.Service) (*globalmcp.Server, error) {
	if cfg.Agent.DefaultWorkspace == "" {
		logger2.
			Info("No default workspace configured, using proxy-only MCP server")
		return globalmcp.NewServer(cfg, logger2, registry), nil
	}
	logger2.
		Info("Default workspace configured, initializing standalone MCP server",
			"workspace", cfg.Agent.DefaultWorkspace,
			"repo", cfg.Agent.DefaultWorkspaceRepo)

	repo, err := getOrCreateDefaultRepo(ctx, store, cfg.Agent.DefaultWorkspaceRepo, cfg.Agent.DefaultWorkspace, logger2)
	if err != nil {
		logger2.
			Error("Failed to setup default workspace", "error", err)
		return nil, fmt.Errorf("failed to setup default workspace: %w", err)
	}

	scopedStore := vectorStore.ForRepo(repo.QdrantCollectionName, cfg.AI.EmbedderModel)

	standaloneCfg := &globalmcp.StandaloneConfig{
		Store:       store,
		VectorStore: scopedStore,
		RAGService:  ragService,
		Repo:        repo,
		RepoConfig:  core.DefaultRepoConfig(),
	}

	return globalmcp.NewStandaloneServer(cfg, logger2, registry, standaloneCfg), nil
}

func getOrCreateDefaultRepo(ctx context.Context, store storage.Store, repoFullName, repoPath string, logger2 *slog.Logger) (*storage.Repository, error) {
	repo, err := store.GetRepositoryByFullName(ctx, repoFullName)
	if err != nil {
		return nil, fmt.Errorf("failed to check for existing repository: %w", err)
	}

	if repo != nil {
		logger2.
			Info("Found existing repository record for default workspace", "repo", repoFullName)
		return repo, nil
	}
	logger2.
		Info("Creating new repository record for default workspace", "repo", repoFullName)

	collectionName := repomanager.GenerateCollectionName(repoFullName)
	repo = &storage.Repository{
		FullName:             repoFullName,
		ClonePath:            repoPath,
		QdrantCollectionName: collectionName,
	}

	if err := store.CreateRepository(ctx, repo); err != nil {
		return nil, fmt.Errorf("failed to create repository record: %w", err)
	}

	return repo, nil
}

func provideWorkspaceRegistry(logger2 *slog.Logger) *globalmcp.WorkspaceRegistry {
	return globalmcp.NewWorkspaceRegistry(logger2)
}

func provideReranker(ctx context.Context, cfg *config.Config, logger2 *slog.Logger, promptMgr *llm.PromptManager) (schema.Reranker, error) {
	if !cfg.AI.EnableReranking {
		logger2.
			Info("Reranking is disabled, using NoOpReranker")
		return schema.NoOpReranker{}, nil
	}
	logger2.
		Info("Initializing LLM Reranker", "model", cfg.AI.RerankerModel)

	headerTimeout := parseHeaderTimeout(cfg.AI.HTTPResponseHeaderTimeout, logger2)
	requestTimeout := parseRequestTimeout(cfg.AI.HTTPRequestTimeout, logger2)
	logger2.
		Info("configuring Ollama HTTP client for reranker",
			"response_header_timeout", headerTimeout,
			"request_timeout", requestTimeout,
			"model", cfg.AI.RerankerModel,
		)

	clientCfg := httpclient.NewConfig(httpclient.WithResponseHeaderTimeout(headerTimeout))

	if requestTimeout > 0 {
		clientCfg.Timeout = requestTimeout
	} else {
		clientCfg.Timeout = 0
	}

	opts := []ollama.Option{ollama.WithServerURL(cfg.AI.OllamaHost), ollama.WithModel(cfg.AI.RerankerModel), ollama.WithHTTPClient(httpclient.NewClient(clientCfg)), ollama.WithLogger(logger2), ollama.WithRetryAttempts(3), ollama.WithRetryDelay(2 * time.Second)}

	if cfg.AI.ModelKeepAlive != "" {
		opts = append(opts, ollama.WithKeepAlive(cfg.AI.ModelKeepAlive))
	}

	rerankLLM, err := ollama.New(opts...)
	if err != nil {
		return nil, fmt.Errorf("failed to create reranker LLM: %w", err)
	}

	prompt, err := promptMgr.Raw("rerank_precision")
	if err != nil {
		logger2.Warn("failed to load rerank prompt, using default", "error", err)
		return llms.NewLLMReranker(rerankLLM, llms.WithConcurrency(3)), nil
	}

	logger2.Debug("Loaded rerank prompt", "prompt_len", len(prompt))
	return llms.NewLLMReranker(rerankLLM, llms.WithConcurrency(3), llms.WithPrompt(prompt)), nil
}
