// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"
	"fmt"
	"github.com/jmoiron/sqlx"
	"github.com/sevigo/code-warden/internal/app"
	"github.com/sevigo/code-warden/internal/config"
	"github.com/sevigo/code-warden/internal/core"
	"github.com/sevigo/code-warden/internal/db"
	"github.com/sevigo/code-warden/internal/gitutil"
	"github.com/sevigo/code-warden/internal/globalmcp"
	"github.com/sevigo/code-warden/internal/jobs"
	"github.com/sevigo/code-warden/internal/llm"
	"github.com/sevigo/code-warden/internal/logger"
	"github.com/sevigo/code-warden/internal/repomanager"
	"github.com/sevigo/code-warden/internal/server"
	"github.com/sevigo/code-warden/internal/storage"
	"github.com/sevigo/goframe/llms"
	"io"
	"log/slog"
	"os"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context) (*app.App, func(), error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return nil, nil, err
	}
	dbConfig := provideDBConfig(configConfig)
	dbDB, cleanup, err := db.NewDatabase(dbConfig)
	if err != nil {
		return nil, nil, err
	}
	sqlxDB := provideSQLXDB(dbDB)
	store := storage.NewStore(sqlxDB)
	loggerConfig := provideLoggerConfig(configConfig)
	writer := provideLogWriter(configConfig)
	logger := provideSlogLogger(loggerConfig, writer)
	client := gitutil.NewClient(logger)
	repoManager := repomanager.New(configConfig, store, client, logger)
	workspaceRegistry := provideWorkspaceRegistry(logger)
	model, err := provideGeneratorLLM(ctx, configConfig, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	promptManager, err := llm.NewPromptManager()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	reviewJob := jobs.NewReviewJob(configConfig, store, repoManager, logger, workspaceRegistry, model, promptManager)
	jobDispatcher := jobs.NewDispatcher(ctx, reviewJob, configConfig, logger)
	serverServer := server.NewServerWithStore(ctx, configConfig, jobDispatcher, reviewJob, store, repoManager, client, logger)
	globalmcpServer, err := provideGlobalMCPServer(ctx, configConfig, logger, workspaceRegistry, store)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	appApp := app.NewApp(configConfig, dbDB, store, repoManager, jobDispatcher, serverServer, client, globalmcpServer, logger)
	return appApp, func() {
		cleanup()
	}, nil
}

// wire.go:

func provideSQLXDB(db2 *db.DB) *sqlx.DB {
	return db2.DB
}

func provideGeneratorLLM(ctx context.Context, cfg *config.Config, logger *slog.Logger) (llms.Model, error) {
	return llm.NewGenerator(ctx, cfg.AI, logger)
}

func provideLoggerConfig(cfg *config.Config) logger.Config {
	return cfg.Logging
}

func provideDBConfig(cfg *config.Config) *config.DBConfig {
	return &cfg.Database
}

func provideLogWriter(cfg *config.Config) io.Writer {
	switch cfg.Logging.Output {
	case "stdout":
		return os.Stdout
	case "stderr":
		return os.Stderr
	case "file":
		f, err := os.OpenFile("code-warden.log", os.O_WRONLY|os.O_CREATE|os.O_APPEND, 0600)
		if err != nil {
			fmt.Fprintf(os.Stderr, "failed to open log file: %v, falling back to stdout\n", err)
			return os.Stdout
		}
		return f
	default:
		return os.Stdout
	}
}

func provideSlogLogger(loggerConfig logger.Config, writer io.Writer) *slog.Logger {
	return logger.NewLogger(loggerConfig, writer)
}

func provideGlobalMCPServer(ctx context.Context, cfg *config.Config, logger2 *slog.Logger, registry *globalmcp.WorkspaceRegistry, store storage.Store) (*globalmcp.Server, error) {
	if cfg.Agent.DefaultWorkspace == "" {
		logger2.
			Info("No default workspace configured, using proxy-only MCP server")
		return globalmcp.NewServer(cfg, logger2, registry), nil
	}
	logger2.
		Info("Default workspace configured, initializing standalone MCP server",
			"workspace", cfg.Agent.DefaultWorkspace,
			"repo", cfg.Agent.DefaultWorkspaceRepo)

	repo, err := getOrCreateDefaultRepo(ctx, store, cfg.Agent.DefaultWorkspaceRepo, cfg.Agent.DefaultWorkspace, logger2)
	if err != nil {
		logger2.
			Error("Failed to setup default workspace", "error", err)
		return nil, fmt.Errorf("failed to setup default workspace: %w", err)
	}

	standaloneCfg := &globalmcp.StandaloneConfig{
		Store:      store,
		Repo:       repo,
		RepoConfig: core.DefaultRepoConfig(),
	}

	return globalmcp.NewStandaloneServer(cfg, logger2, registry, standaloneCfg), nil
}

func getOrCreateDefaultRepo(ctx context.Context, store storage.Store, repoFullName, repoPath string, logger2 *slog.Logger) (*storage.Repository, error) {
	repo, err := store.GetRepositoryByFullName(ctx, repoFullName)
	if err != nil {
		return nil, fmt.Errorf("failed to check for existing repository: %w", err)
	}

	if repo != nil {
		logger2.
			Info("Found existing repository record for default workspace", "repo", repoFullName)
		return repo, nil
	}
	logger2.
		Info("Creating new repository record for default workspace", "repo", repoFullName)

	repo = &storage.Repository{
		FullName:  repoFullName,
		ClonePath: repoPath,
	}

	if err := store.CreateRepository(ctx, repo); err != nil {
		return nil, fmt.Errorf("failed to create repository record: %w", err)
	}

	return repo, nil
}

func provideWorkspaceRegistry(logger2 *slog.Logger) *globalmcp.WorkspaceRegistry {
	return globalmcp.NewWorkspaceRegistry(logger2)
}
