// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sevigo/code-warden/internal/storage (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_store.go -package=mocks github.com/sevigo/code-warden/internal/storage Store
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	core "github.com/sevigo/code-warden/internal/core"
	storage "github.com/sevigo/code-warden/internal/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CreateRepository mocks base method.
func (m *MockStore) CreateRepository(ctx context.Context, repo *storage.Repository) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRepository", ctx, repo)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRepository indicates an expected call of CreateRepository.
func (mr *MockStoreMockRecorder) CreateRepository(ctx, repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRepository", reflect.TypeOf((*MockStore)(nil).CreateRepository), ctx, repo)
}

// DeleteFiles mocks base method.
func (m *MockStore) DeleteFiles(ctx context.Context, repoID int64, paths []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFiles", ctx, repoID, paths)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFiles indicates an expected call of DeleteFiles.
func (mr *MockStoreMockRecorder) DeleteFiles(ctx, repoID, paths any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFiles", reflect.TypeOf((*MockStore)(nil).DeleteFiles), ctx, repoID, paths)
}

// GetAllRepositories mocks base method.
func (m *MockStore) GetAllRepositories(ctx context.Context) ([]*storage.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllRepositories", ctx)
	ret0, _ := ret[0].([]*storage.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllRepositories indicates an expected call of GetAllRepositories.
func (mr *MockStoreMockRecorder) GetAllRepositories(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllRepositories", reflect.TypeOf((*MockStore)(nil).GetAllRepositories), ctx)
}

// GetAllReviewsForPR mocks base method.
func (m *MockStore) GetAllReviewsForPR(ctx context.Context, repoFullName string, prNumber int) ([]*core.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllReviewsForPR", ctx, repoFullName, prNumber)
	ret0, _ := ret[0].([]*core.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllReviewsForPR indicates an expected call of GetAllReviewsForPR.
func (mr *MockStoreMockRecorder) GetAllReviewsForPR(ctx, repoFullName, prNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllReviewsForPR", reflect.TypeOf((*MockStore)(nil).GetAllReviewsForPR), ctx, repoFullName, prNumber)
}

// GetFilesForRepo mocks base method.
func (m *MockStore) GetFilesForRepo(ctx context.Context, repoID int64) (map[string]storage.FileRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilesForRepo", ctx, repoID)
	ret0, _ := ret[0].(map[string]storage.FileRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilesForRepo indicates an expected call of GetFilesForRepo.
func (mr *MockStoreMockRecorder) GetFilesForRepo(ctx, repoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilesForRepo", reflect.TypeOf((*MockStore)(nil).GetFilesForRepo), ctx, repoID)
}

// GetLatestReviewForPR mocks base method.
func (m *MockStore) GetLatestReviewForPR(ctx context.Context, repoFullName string, prNumber int) (*core.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestReviewForPR", ctx, repoFullName, prNumber)
	ret0, _ := ret[0].(*core.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestReviewForPR indicates an expected call of GetLatestReviewForPR.
func (mr *MockStoreMockRecorder) GetLatestReviewForPR(ctx, repoFullName, prNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestReviewForPR", reflect.TypeOf((*MockStore)(nil).GetLatestReviewForPR), ctx, repoFullName, prNumber)
}

// GetRepositoryByClonePath mocks base method.
func (m *MockStore) GetRepositoryByClonePath(ctx context.Context, clonePath string) (*storage.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepositoryByClonePath", ctx, clonePath)
	ret0, _ := ret[0].(*storage.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositoryByClonePath indicates an expected call of GetRepositoryByClonePath.
func (mr *MockStoreMockRecorder) GetRepositoryByClonePath(ctx, clonePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositoryByClonePath", reflect.TypeOf((*MockStore)(nil).GetRepositoryByClonePath), ctx, clonePath)
}

// GetRepositoryByID mocks base method.
func (m *MockStore) GetRepositoryByID(ctx context.Context, id int64) (*storage.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepositoryByID", ctx, id)
	ret0, _ := ret[0].(*storage.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositoryByID indicates an expected call of GetRepositoryByID.
func (mr *MockStoreMockRecorder) GetRepositoryByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositoryByID", reflect.TypeOf((*MockStore)(nil).GetRepositoryByID), ctx, id)
}

// GetRepositoryByFullName mocks base method.
func (m *MockStore) GetRepositoryByFullName(ctx context.Context, fullName string) (*storage.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepositoryByFullName", ctx, fullName)
	ret0, _ := ret[0].(*storage.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositoryByFullName indicates an expected call of GetRepositoryByFullName.
func (mr *MockStoreMockRecorder) GetRepositoryByFullName(ctx, fullName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositoryByFullName", reflect.TypeOf((*MockStore)(nil).GetRepositoryByFullName), ctx, fullName)
}

// GetScanState mocks base method.
func (m *MockStore) GetScanState(ctx context.Context, repoID int64) (*storage.ScanState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScanState", ctx, repoID)
	ret0, _ := ret[0].(*storage.ScanState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScanState indicates an expected call of GetScanState.
func (mr *MockStoreMockRecorder) GetScanState(ctx, repoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScanState", reflect.TypeOf((*MockStore)(nil).GetScanState), ctx, repoID)
}

// SaveReview mocks base method.
func (m *MockStore) SaveReview(ctx context.Context, review *core.Review) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveReview", ctx, review)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveReview indicates an expected call of SaveReview.
func (mr *MockStoreMockRecorder) SaveReview(ctx, review any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveReview", reflect.TypeOf((*MockStore)(nil).SaveReview), ctx, review)
}

// UpdateRepository mocks base method.
func (m *MockStore) UpdateRepository(ctx context.Context, repo *storage.Repository) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRepository", ctx, repo)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRepository indicates an expected call of UpdateRepository.
func (mr *MockStoreMockRecorder) UpdateRepository(ctx, repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRepository", reflect.TypeOf((*MockStore)(nil).UpdateRepository), ctx, repo)
}

// UpsertFiles mocks base method.
func (m *MockStore) UpsertFiles(ctx context.Context, repoID int64, files []storage.FileRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertFiles", ctx, repoID, files)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertFiles indicates an expected call of UpsertFiles.
func (mr *MockStoreMockRecorder) UpsertFiles(ctx, repoID, files any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertFiles", reflect.TypeOf((*MockStore)(nil).UpsertFiles), ctx, repoID, files)
}

// UpsertScanState mocks base method.
func (m *MockStore) UpsertScanState(ctx context.Context, state *storage.ScanState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertScanState", ctx, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertScanState indicates an expected call of UpsertScanState.
func (mr *MockStoreMockRecorder) UpsertScanState(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertScanState", reflect.TypeOf((*MockStore)(nil).UpsertScanState), ctx, state)
}

func (m *MockStore) GetReviewsForRepo(ctx context.Context, repoFullName string) ([]*core.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReviewsForRepo", ctx, repoFullName)
	ret0, _ := ret[0].([]*core.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockStoreMockRecorder) GetReviewsForRepo(ctx, repoFullName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReviewsForRepo", reflect.TypeOf((*MockStore)(nil).GetReviewsForRepo), ctx, repoFullName)
}

func (m *MockStore) GetReviewStats(ctx context.Context) (*storage.ReviewStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReviewStats", ctx)
	ret0, _ := ret[0].(*storage.ReviewStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockStoreMockRecorder) GetReviewStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReviewStats", reflect.TypeOf((*MockStore)(nil).GetReviewStats), ctx)
}

func (m *MockStore) InsertJobRun(ctx context.Context, job *storage.JobRun) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertJobRun", ctx, job)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockStoreMockRecorder) InsertJobRun(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertJobRun", reflect.TypeOf((*MockStore)(nil).InsertJobRun), ctx, job)
}

func (m *MockStore) UpdateJobRun(ctx context.Context, id int64, status string, completedAt time.Time, durationMs int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateJobRun", ctx, id, status, completedAt, durationMs)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockStoreMockRecorder) UpdateJobRun(ctx, id, status, completedAt, durationMs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateJobRun", reflect.TypeOf((*MockStore)(nil).UpdateJobRun), ctx, id, status, completedAt, durationMs)
}

func (m *MockStore) ListJobRuns(ctx context.Context, limit, offset int) ([]*storage.JobRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListJobRuns", ctx, limit, offset)
	ret0, _ := ret[0].([]*storage.JobRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockStoreMockRecorder) ListJobRuns(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListJobRuns", reflect.TypeOf((*MockStore)(nil).ListJobRuns), ctx, limit, offset)
}
