// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sevigo/goframe/schema (interfaces: Reranker)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_reranker.go -package=mocks github.com/sevigo/goframe/schema Reranker
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	schema "github.com/sevigo/goframe/schema"
	gomock "go.uber.org/mock/gomock"
)

// MockReranker is a mock of Reranker interface.
type MockReranker struct {
	ctrl     *gomock.Controller
	recorder *MockRerankerMockRecorder
	isgomock struct{}
}

// MockRerankerMockRecorder is the mock recorder for MockReranker.
type MockRerankerMockRecorder struct {
	mock *MockReranker
}

// NewMockReranker creates a new mock instance.
func NewMockReranker(ctrl *gomock.Controller) *MockReranker {
	mock := &MockReranker{ctrl: ctrl}
	mock.recorder = &MockRerankerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReranker) EXPECT() *MockRerankerMockRecorder {
	return m.recorder
}

// Rerank mocks base method.
func (m *MockReranker) Rerank(ctx context.Context, query string, docs []schema.Document) ([]schema.ScoredDocument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rerank", ctx, query, docs)
	ret0, _ := ret[0].([]schema.ScoredDocument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Rerank indicates an expected call of Rerank.
func (mr *MockRerankerMockRecorder) Rerank(ctx, query, docs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rerank", reflect.TypeOf((*MockReranker)(nil).Rerank), ctx, query, docs)
}
