// Package core defines the essential interfaces and data structures that form the
// backbone of the application. These components are designed to be abstract,
// allowing for flexible and decoupled implementations of the application's logic.
package core

import "time"

const (
	// VerdictApprove indicates the code review should be approved.
	VerdictApprove = "APPROVE"
	// VerdictRequestChanges indicates requested changes before approval.
	VerdictRequestChanges = "REQUEST_CHANGES"
	// VerdictComment indicates general comments without approval decision.
	VerdictComment = "COMMENT"
)

// Review represents a single code review stored in the database.
// Each review contains the content generated by the LLM, associated metadata
// such as the pull request number and commit SHA, and timestamps for tracking.
type Review struct {
	// ID is the database primary key.
	ID int64 `db:"id"`
	// RepoFullName is the full repository name in "owner/repo" format.
	RepoFullName string `db:"repo_full_name"`
	// PRNumber is the GitHub pull request number.
	PRNumber int `db:"pr_number"`
	// HeadSHA is the commit SHA of the PR's head at the time of review.
	HeadSHA string `db:"head_sha"`
	// ReviewContent is the raw content of the review generated by the LLM.
	ReviewContent string `db:"review_content"`
	// CreatedAt is the timestamp when the review was created.
	CreatedAt time.Time `db:"created_at"`
}

// ReReviewData is a type-safe struct for rendering re-review prompts.
// It contains all the context needed for the LLM to perform a follow-up
// review of changes since a previous review was generated.
type ReReviewData struct {
	// Language is the programming language of the repository.
	Language string
	// OriginalReview is the content of the previous review being followed up on.
	OriginalReview string
	// NewDiff contains the code changes since the original review.
	NewDiff string
	// UserInstructions are optional custom guidance provided by the user.
	UserInstructions string
	// Context is the repository context retrieved from the vector store.
	Context string
	// Definitions contains resolved type definitions for the changed code.
	Definitions string
}
