#!/usr/bin/env bash
# scripts/llm-context.sh — bundle the project structure, core Go source, and
# docs into one Markdown file for pasting into an LLM context window.
#
# Skips tests, mocks, generated code, the UI, and config/schema files — only
# what a reader needs to understand the system.
#
# Usage: bash scripts/llm-context.sh [output-file]   (default: llm-context.md)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${1:-$REPO_ROOT/llm-context.md}"

cd "$REPO_ROOT"

# Directories/files never worth including, tree or content.
PRUNE_DIRS=(.git node_modules ui bin data keys reviews review-traces vendor .go_cache dist coverage)

is_pruned_dir() {
    local d="$1"
    for p in "${PRUNE_DIRS[@]}"; do
        [[ "$d" == "$p" || "$d" == */"$p" || "$d" == "$p"/* ]] && return 0
    done
    return 1
}

print_tree() {
    local dir="$1" prefix="$2"
    local entries=()
    while IFS= read -r -d '' entry; do
        entries+=("$entry")
    done < <(find "$dir" -mindepth 1 -maxdepth 1 -print0 | sort -z)

    local count=${#entries[@]} i=0
    for entry in "${entries[@]}"; do
        i=$((i + 1))
        local name rel connector next_prefix
        name="$(basename "$entry")"
        rel="${entry#"$REPO_ROOT"/}"
        [[ "$name" == .* ]] && continue
        if is_pruned_dir "$rel"; then
            continue
        fi
        if [[ $i -eq $count ]]; then
            connector="└── "
            next_prefix="${prefix}    "
        else
            connector="├── "
            next_prefix="${prefix}│   "
        fi
        if [[ -d "$entry" ]]; then
            echo "${prefix}${connector}${name}/"
            print_tree "$entry" "$next_prefix"
        else
            echo "${prefix}${connector}${name}"
        fi
    done
}

lang_for() {
    case "$1" in
    *.go) echo "go" ;;
    *.md) echo "markdown" ;;
    *.prompt) echo "text" ;;
    *) echo "" ;;
    esac
}

{
    echo "# Code-Warden — LLM context"
    echo
    echo "Generated by scripts/llm-context.sh. Project structure, core Go source, and docs only — no tests, mocks, generated code, UI, or config/schema files."
    echo
    echo "## Project structure"
    echo
    echo '```'
    echo "code-warden/"
    print_tree "$REPO_ROOT" ""
    echo '```'
    echo

    echo "## Documentation"

    doc_files=(
        README.md AGENTS.md CLAUDE.md CONTRIBUTING.md
        docs/ARCHITECTURE.md docs/DISCOVERY_ARCHITECTURE.md docs/ROADMAP.md
        docs/SETUP.md docs/TROUBLESHOOTING.md
    )
    for f in "${doc_files[@]}"; do
        [[ -f "$f" ]] || continue
        echo
        echo "### $f"
        echo
        echo '```markdown'
        cat "$f"
        echo '```'
    done

    echo
    echo "## Prompts"

    while IFS= read -r -d '' f; do
        rel="${f#"$REPO_ROOT"/}"
        echo
        echo "### $rel"
        echo
        echo '```text'
        cat "$f"
        echo '```'
    done < <(find internal/llm/prompts -name "*.prompt" -print0 2>/dev/null | sort -z)

    echo
    echo "## Go source"
    echo
    echo "cmd/ and internal/, excluding *_test.go, mocks/, and internal/wire/wire_gen.go."

    while IFS= read -r -d '' f; do
        rel="${f#"$REPO_ROOT"/}"
        case "$rel" in
        *_test.go | mocks/* | internal/wire/wire_gen.go) continue ;;
        esac
        echo
        echo "### $rel"
        echo
        echo '```go'
        cat "$f"
        echo '```'
    done < <(find cmd internal -name "*.go" -print0 | sort -z)

} >"$OUT"

file_count=$(grep -c '^### ' "$OUT" || true)
size=$(wc -c <"$OUT" | tr -d ' ')
echo "Wrote $OUT ($file_count files, ${size} bytes)"
